/* ═══════════════════════════════════════════════════════════
   VOSKHOD — банк SAT-слов. Каждое: id, word, definition,
   example, distractors[3]. Определение на русском + синоним.
   ═══════════════════════════════════════════════════════════ */

window.VOCAB_BANK = [
  {id:'w1',word:'ambiguous',def:'имеющий несколько значений, неясный',ex:'The ambiguous answer confused everyone.',d:['явный','агрессивный','амбициозный']},
  {id:'w2',word:'pragmatic',def:'практичный, ориентированный на результат',ex:'She took a pragmatic approach to the problem.',d:['идеалистичный','дорогой','временный']},
  {id:'w3',word:'meticulous',def:'крайне тщательный, дотошный',ex:'His meticulous notes impressed the professor.',d:['небрежный','быстрый','грубый']},
  {id:'w4',word:'buttress',def:'подкреплять, поддерживать',ex:'Data buttressed the hypothesis.',d:['подрывать','игнорировать','отменять']},
  {id:'w5',word:'lucid',def:'ясный, понятный',ex:'A lucid explanation made it simple.',d:['запутанный','многословный','скучный']},
  {id:'w6',word:'undermine',def:'подрывать, ослаблять',ex:'Rumors undermined her authority.',d:['усиливать','поддерживать','измерять']},
  {id:'w7',word:'corroborate',def:'подтверждать, подтверждать доказательствами',ex:'Two witnesses corroborated the story.',d:['противоречить','оспаривать','игнорировать']},
  {id:'w8',word:'conventional',def:'обычный, традиционный',ex:'A conventional approach worked fine.',d:['необычный','радикальный','гениальный']},
  {id:'w9',word:'unorthodox',def:'необычный, нестандартный',ex:'His unorthodox method surprised everyone.',d:['традиционный','осторожный','известный']},
  {id:'w10',word:'explicit',def:'выраженный прямо, недвусмысленный',ex:'The instructions were explicit.',d:['скрытый','сложный','устный']},
  {id:'w11',word:'redundant',def:'избыточный, повторяющий',ex:'Cut the redundant paragraphs.',d:['краткий','красивый','точный']},
  {id:'w12',word:'substantial',def:'значительный, существенный',ex:'Substantial evidence was presented.',d:['незначительный','фальшивый','редкий']},
  {id:'w13',word:'advocate',def:'выступать за, поддерживать',ex:'She advocates for education reform.',d:['критиковать','избегать','продавать']},
  {id:'w14',word:'implement',def:'внедрять, осуществлять',ex:'The policy was implemented last year.',d:['предложить','отменить','критиковать']},
  {id:'w15',word:'disperse',def:'рассеивать, разбрасывать',ex:'The crowd dispersed quickly.',d:['собрать','усилить','направить']},
  {id:'w16',word:'innovative',def:'новаторский, новаторский',ex:'An innovative solution won the prize.',d:['старый','скучный','дорогой']},
  {id:'w17',word:'compelling',def:'убедительный, неотразимый',ex:'A compelling argument changed minds.',d:['слабый','скучный','непонятный']},
  {id:'w18',word:'profound',def:'глубокий, сильный',ex:'A profound impact on society.',d:['поверхностный','лёгкий','редкий']},
  {id:'w19',word:'tentative',def:'предварительный, неокончательный',ex:'A tentative agreement was reached.',d:['окончательный','уверенный','жёсткий']},
  {id:'w20',word:'rigorous',def:'строгий, тщательный',ex:'Rigorous testing ensured quality.',d:['мягкий','быстрый','небрежный']},
  {id:'w21',word:'coherent',def:'связный, логичный',ex:'A coherent argument convinced the jury.',d:['противоречивый','скучный','короткий']},
  {id:'w22',word:'facilitate',def:'способствовать, облегчать',ex:'Technology facilitates learning.',d:['препятствовать','запрещать','усложнять']},
  {id:'w23',word:'prevalent',def:'распространённый, преобладающий',ex:'The disease is prevalent in tropical areas.',d:['редкий','опасный','новый']},
  {id:'w24',word:'scrutinize',def:'тщательно изучать',ex:'The committee scrutinized every detail.',d:['игнорировать','хвалить','упрощать']},
  {id:'w25',word:'tentative',def:'неуверенный, осторожный',ex:'She made a tentative suggestion.',d:['уверенный','смелый','резкий']},
  {id:'w26',word:'versatile',def:'разносторонний, универсальный',ex:'A versatile tool for many tasks.',d:['односторонний','хрупкий','редкий']},
  {id:'w27',word:'paradigm',def:'парадигма, образец',ex:'A new paradigm in physics emerged.',d:['проблема','ошибка','устаревшая модель']},
  {id:'w28',word:'refute',def:'опровергать',ex:'The data refuted the earlier claim.',d:['подтвердить','поддержать','объяснить']},
  {id:'w29',word:'nuance',def:'тонкий оттенок, нюанс',ex:'The nuance was lost in translation.',d:['грубость','основная идея','шум']},
  {id:'w30',word:'skeptical',def:'скептический, сомневающийся',ex:'Scientists were skeptical about the results.',d:['уверенный','доверчивый','восторженный']},
  {id:'w31',word:'diligent',def:'усердный, старательный',ex:'A diligent student earned top marks.',d:['ленивый','грубый','невнимательный']},
  {id:'w32',word:'feasible',def:'осуществимый, реальный',ex:'A feasible plan within budget.',d:['невозможный','дорогой','рискованный']},
  {id:'w33',word:'inevitable',def:'неизбежный',ex:'Change is inevitable.',d:['маловероятный','редкий','предотвратимый']},
  {id:'w34',word:'supersede',def:'заменять, вытеснять',ex:'The new law supersedes the old one.',d:['поддерживать','дополнять','предшествовать']},
  {id:'w35',word:'volatile',def:'нестабильный, изменчивый',ex:'Volatile markets worry investors.',d:['стабильный','предсказуемый','спокойный']},
  {id:'w36',word:'eloquent',def:'красноречивый',ex:'An eloquent speech moved the audience.',d:['косноязычный','громкий','скучный']},
  {id:'w37',word:'mitigate',def:'смягчать, уменьшать',ex:'Steps to mitigate the damage.',d:['усугубить','вызвать','игнорировать']},
  {id:'w38',word:'austere',def:'строгий, аскетичный',ex:'An austere lifestyle choice.',d:['роскошный','тёплый','весёлый']},
  {id:'w39',word:'deter',def:'отговаривать, удерживать',ex:'Signs deter trespassers.',d:['поощрять','приглашать','убеждать']},
  {id:'w40',word:'emphasize',def:'подчёркивать, акцентировать',ex:'The report emphasizes safety.',d:['игнорировать','скрывать','отрицать']},
  {id:'w41',word:'comprehensive',def:'всеобъемлющий, полный',ex:'A comprehensive review of the field.',d:['частичный','поверхностный','краткий']},
  {id:'w42',word:'vindicate',def:'оправдывать, защищать',ex:'New evidence vindicated the defendant.',d:['осудить','обвинить','подозревать']},
  {id:'w43',word:'resilient',def:'стойкий, быстро восстанавливающийся',ex:'A resilient economy bounced back.',d:['хрупкий','слабый','мягкий']},
  {id:'w44',word:'transparent',def:'прозрачный, открытый',ex:'A transparent process builds trust.',d:['скрытый','сложный','непонятный']},
  {id:'w45',word:'rigid',def:'жёсткий, негибкий',ex:'Rigid rules stifle creativity.',d:['гибкий','мягкий','простой']},
  {id:'w46',word:'discrepancy',def:'расхождение, несоответствие',ex:'A discrepancy between the two reports.',d:['совпадение','точность','похожесть']},
  {id:'w47',word:'augment',def:'увеличивать, дополнять',ex:'Augment the team with experts.',d:['уменьшить','заменить','убрать']},
  {id:'w48',word:'reluctant',def:'неохотный, сопротивляющийся',ex:'Reluctant to share the data.',d:['охотный','готовый','радостный']},
  {id:'w49',word:'arbitrary',def:'произвольный, случайный',ex:'An arbitrary decision without explanation.',d:['обоснованный','логичный','справедливый']},
  {id:'w50',word:'assert',def:'утверждать, заявлять',ex:'He asserted his innocence.',d:['отрицать','сомневаться','спрашивать']},
  {id:'w51',word:'candid',def:'искренний, прямой',ex:'A candid discussion about risks.',d:['лицемерный','скрытный','вежливый']},
  {id:'w52',word:'deteriorate',def:'ухудшаться',ex:'The building deteriorated over years.',d:['улучшиться','восстановиться','укрепиться']},
  {id:'w53',word:'empirical',def:'эмпирический, основанный на опыте',ex:'Empirical data supports the theory.',d:['теоретический','случайный','умозрительный']},
  {id:'w54',word:'exaggerate',def:'преувеличивать',ex:'Don’t exaggerate the risks.',d:['приуменьшить','описать','скрыть']},
  {id:'w55',word:'indifferent',def:'безразличный, равнодушный',ex:'Indifferent to the outcome.',d:['заинтересованный','взволнованный','злой']},
  {id:'w56',word:'inherent',def:'присущий, врождённый',ex:'Inherent risks in any investment.',d:['внешний','случайный','добавленный']},
  {id:'w57',word:'meddle',def:'вмешиваться, лезть не в своё дело',ex:'Don’t meddle in their affairs.',d:['игнорировать','помогать','избегать']},
  {id:'w58',word:'notorious',def:'печально известный',ex:'A notorious criminal was caught.',d:['уважаемый','неизвестный','любимый']},
  {id:'w59',word:'obscure',def:'неясный, тёмный',ex:'An obscure reference puzzled readers.',d:['ясный','известный','простой']},
  {id:'w60',word:'plausible',def:'правдоподобный',ex:'A plausible explanation for the delay.',d:['невероятный','абсурдный','доказанный']},
  {id:'w61',word:'quaint',def:'своеобразный, старомодный',ex:'A quaint village with cobblestone streets.',d:['современный','огромный','грязный']},
  {id:'w62',word:'rebuff',def:'отклонять, давать отпор',ex:'Her offer was rebuffed.',d:['принять','поддержать','обсудить']},
  {id:'w63',word:'scrupulous',def:'добросовестный, принципиальный',ex:'A scrupulous review of the data.',d:['небрежный','ленивый','грубый']},
  {id:'w64',word:'spur',def:'стимулировать, побуждать',ex:'The crisis spurred innovation.',d:['остановить','запретить','отложить']},
  {id:'w65',word:'stifling',def:'удушающий, подавляющий',ex:'Stifling heat made work impossible.',d:['свежий','приятный','прохладный']},
  {id:'w66',word:'superfluous',def:'излишний, лишний',ex:'Cut superfluous details from the report.',d:['необходимый','важный','краткий']},
  {id:'w67',word:'taciturn',def:'молчаливый, немногословный',ex:'A taciturn man of few words.',d:['болтливый','громкий','весёлый']},
  {id:'w68',word:'trivial',def:'тривиальный, малозначительный',ex:'Don’t waste time on trivial details.',d:['важный','сложный','редкий']},
  {id:'w69',word:'venerate',def:'почитать, уважать',ex:'The founder is venerated by employees.',d:['презирать','критиковать','игнорировать']},
  {id:'w70',word:'wary',def:'осторожный, настороженный',ex:'Be wary of quick fixes.',d:['доверчивый','смелый','небрежный']},
  {id:'w71',word:'alleviate',def:'облегчать, смягчать',ex:'Medication alleviated the pain.',d:['усилить','вызвать','спровоцировать']},
  {id:'w72',word:'antagonize',def:'противодействовать, раздражать',ex:'Don’t antagonize your allies.',d:['поддержать','успокоить','игнорировать']},
  {id:'w73',word:'coincide',def:'совпадать',ex:'The events coincide with the festival.',d:['противоречить','отличаться','предшествовать']},
  {id:'w74',word:'condescending',def:'высокомерный, снисходительный',ex:'A condescending tone offended the team.',d:['уважительный','скромный','дружелюбный']},
  {id:'w75',word:'debunk',def:'разоблачать, развенчивать',ex:'The study debunked the popular myth.',d:['подтвердить','распространить','поддержать']},
  {id:'w76',word:'dubious',def:'сомнительный',ex:'A dubious claim without evidence.',d:['надёжный','доказанный','честный']},
  {id:'w77',word:'erode',def:'разрушать, подтачивать',ex:'Waves eroded the cliff over centuries.',d:['укрепить','построить','создать']},
  {id:'w78',word:'exemplify',def:'служить примером, демонстрировать',ex:'Her career exemplifies dedication.',d:['противоречить','преуменьшать','скрывать']},
  {id:'w79',word:'frivolous',def:'легкомысленный, несерьёзный',ex:'A frivolous complaint wasted time.',d:['серьёзный','важный','обоснованный']},
  {id:'w80',word:'hostile',def:'враждебный, недружелюбный',ex:'A hostile reaction to the proposal.',d:['дружелюбный','нейтральный','тёплый']},
  {id:'w81',word:'impartial',def:'беспристрастный, объективный',ex:'An impartial judge is essential.',d:['предвзятый','пристрастный','нечестный']},
  {id:'w82',word:'incredulous',def:'недоверчивый',ex:'An incredulous look crossed her face.',d:['доверчивый','убеждённый','удивлённый']},
  {id:'w83',word:'latent',def:'скрытый, потенциальный',ex:'Latent talent waiting to be discovered.',d:['явный','активный','утраченный']},
  {id:'w84',word:'meticulous',def:'тщательный, педантичный',ex:'Meticulous attention to detail.',d:['небрежный','грубый','быстрый']},
  {id:'w85',word:'nostalgia',def:'ностальгия, тоска по прошлому',ex:'A wave of nostalgia hit her.',d:['предвкушение','страх','радость']},
  {id:'w86',word:'obstinate',def:'упрямый, непреклонный',ex:'An obstinate refusal to compromise.',d:['гибкий','покорный','согласный']},
  {id:'w87',word:'prudent',def:'благоразумный, осторожный',ex:'A prudent investment strategy.',d:['безрассудный','рискованный','поспешный']},
  {id:'w88',word:'rebut',def:'опровергать',ex:'The lawyer rebutted each claim.',d:['подтвердить','поддержать','согласиться']},
  {id:'w89',word:'solvent',def:'платёжеспособный',ex:'The company remained solvent despite losses.',d:['банкрот','должник','богатый']},
  {id:'w90',word:'tenacious',def:'упорный, цепкий',ex:'A tenacious pursuit of justice.',d:['слабый','быстро сдающийся','ленивый']},
  {id:'w91',word:'undermine',def:'подрывать, ослаблять',ex:'Criticism can undermine confidence.',d:['поддержать','усилить','построить']},
  {id:'w92',word:'vague',def:'неопределённый, расплывчатый',ex:'A vague answer satisfied no one.',d:['чёткий','точный','конкретный']},
  {id:'w93',word:'zealous',def:'ревностный, страстный',ex:'A zealous advocate for reform.',d:['равнодушный','вялый','скептический']},
  {id:'w94',word:'brusque',def:'резкий, грубоватый',ex:'A brusque reply surprised the guests.',d:['вежливый','мягкий','дружелюбный']},
  {id:'w95',word:'circumspect',def:'осторожный, осмотрительный',ex:'Be circumspect when signing contracts.',d:['безрассудный','спешащий','легковерный']},
  {id:'w96',word:'debilitate',def:'ослаблять, лишать сил',ex:'The illness debilitated him for weeks.',d:['укрепить','вылечить','оздоровить']},
  {id:'w97',word:'efface',def:'стирать, уничтожать',ex:'Time had effaced the inscription.',d:['выгравировать','создать','усилить']},
  {id:'w98',word:'furtive',def:'тайный, украдкой',ex:'Furtive glances at the document.',d:['открытый','честный','смелый']},
  {id:'w99',word:'impetuous',def:'импульсивный, порывистый',ex:'An impetuous decision he later regretted.',d:['осторожный','спокойный','обдуманный']},
  {id:'w100',word:'laconic',def:'лаконичный, краткий',ex:'A laconic reply: “No.”',d:['многословный','подробный','громкий']},
  {id:'w101',word:'obsequious',def:'угодливый, подобострастный',ex:'Obsequious praise annoyed the manager.',d:['независимый','честный','грубый']},
  {id:'w102',word:'pervasive',def:'всепроникающий, распространённый',ex:'Pervasive influence of social media.',d:['редкий','локальный','ограниченный']},
  {id:'w103',word:'recluse',def:'отшельник, затворник',ex:'The author lived as a recluse.',d:['общественный деятель','экстраверт','лидер']},
  {id:'w104',word:'spurious',def:'фальшивый, поддельный',ex:'Spurious claims were dismissed.',d:['подлинный','доказанный','надёжный']},
  {id:'w105',word:'stoic',def:'стоический, невозмутимый',ex:'A stoic response to criticism.',d:['эмоциональный','плаксивый','восторженный']},
  {id:'w106',word:'tirade',def:'длинная гневная речь',ex:'A tirade against the management.',d:['комплимент','шёпот','вопрос']},
  {id:'w107',word:'undaunted',def:'неустрашимый, непоколебимый',ex:'Undaunted by failure, she tried again.',d:['напуганный','сломленный','осторожный']},
  {id:'w108',word:'waver',def:'колебаться, сомневаться',ex:'His resolve never wavered.',d:['стабильно держаться','упасть','решить']},
  {id:'w109',word:'aesthetic',def:'эстетический, художественный',ex:'The aesthetic appeal of the design.',d:['функциональный','практичный','дешёвый']},
  {id:'w110',word:'belligerent',def:'воинственный, агрессивный',ex:'A belligerent tone escalated the argument.',d:['мирный','дружелюбный','спокойный']},
  {id:'w111',word:'coerce',def:'принуждать, заставлять',ex:'They coerced him into signing.',d:['убедить','освободить','попросить']},
  {id:'w112',word:'dearth',def:'нехватка, дефицит',ex:'A dearth of qualified candidates.',d:['избыток','достаток','разнообразие']},
  {id:'w113',word:'egregious',def:'возмутительный, вопиющий',ex:'An egregious error in the report.',d:['незначительный','приемлемый','хороший']},
  {id:'w114',word:'fortuitous',def:'случайный, удачный',ex:'A fortuitous meeting led to the deal.',d:['запланированный','неудачный','предсказуемый']},
  {id:'w115',word:'garrulous',def:'болтливый, словоохотливый',ex:'A garrulous neighbour who never stops talking.',d:['молчаливый','сдержанный','грубый']},
  {id:'w116',word:'haughty',def:'высокомерный, надменный',ex:'A haughty dismissive attitude.',d:['скромный','дружелюбный','равный']},
  {id:'w117',word:'impeccable',def:'безупречный, не имеющий изъянов',ex:'Impeccable attention to detail.',d:['грязный','плохой','обычный']},
  {id:'w118',word:'juxtapose',def:'сопоставлять, ставить рядом',ex:'The author juxtaposes wealth and poverty.',d:['разделить','смешать','скрыть']},
  {id:'w119',word:'lucrative',def:'прибыльный, доходный',ex:'A lucrative contract for the firm.',d:['убыточный','мелкий','бесплатный']},
  {id:'w120',word:'myopic',def:'близорукий, недальновидный',ex:'A myopic policy ignores long-term effects.',d:['дальновидный','мудрый','осторожный']},
  {id:'w121',word:'nefarious',def:'злодейский, гнусный',ex:'A nefarious plot was uncovered.',d:['добродетельный','честный','обычный']},
  {id:'w122',word:'ostentatious',def:'показной, вычурный',ex:'An ostentatious display of wealth.',d:['скромный','простой','тихий']},
  {id:'w123',word:'placid',def:'спокойный, безмятежный',ex:'A placid lake in the morning.',d:['бурный','глубокий','холодный']},
  {id:'w124',word:'quell',def:'подавлять, успокаивать',ex:'Police quelled the riot.',d:['раздуть','спровоцировать','усилить']},
  {id:'w125',word:'reticent',def:'сдержанный, молчаливый',ex:'Reticent about her past.',d:['болтливый','открытый','громкий']},
  {id:'w126',word:'soporific',def:'усыпляющий, снотворный',ex:'A soporific lecture on tax law.',d:['бодрящий','интересный','громкий']},
  {id:'w127',word:'trepidation',def:'тревога, страх',ex:'She opened the letter with trepidation.',d:['уверенность','радость','спокойствие']},
  {id:'w128',word:'ubiquitous',def:'вездесущий, повсеместный',ex:'Smartphones are ubiquitous today.',d:['редкий','спрятанный','уникальный']},
  {id:'w129',word:'veracity',def:'правдивость, достоверность',ex:'The veracity of the claim was questioned.',d:['ложь','путаница','случайность']},
  {id:'w130',word:'zealot',def:'фанатик, ревностный сторонник',ex:'A zealot who sees no other view.',d:['скептик','равнодушный','колеблющийся']},
];
